#%RAML 1.0 NamedExample

value:
  kartaID: 1
  brojPerona: P1
  brojSedista: A1
  datumPolaska: 2023-06-10
  datumDolaska: 2023-06-11
  korisnik:
    korisnikID: 1
    JMBG: "0101985123456"
    ime: Stefan
    prezime: Nikolić
    adresa: Knez Mihailova 11
    grad: Beograd
  tipKarte:
    tipKarteID: 1
    nazivKarte: Jednosmerna
  ruta:
    rutaID: 1
    mestoDolaska: Beograd
    mestoOdlaska: Novi Sad
    brojPosecenihStanica: 5
  autobus:
    autobusID: 2
    prevoznik: Banat Trans
    tipAutobusa: Standardni
    brojSedista: 50