#%RAML 1.0 NamedExample

value:

  -
    kartaID: 1
    brojPerona: P1
    brojSedista: A1
    datumPolaska: 2023-06-10
    datumDolaska: 2023-06-11
    korisnik:
      korisnikID: 1
      JMBG: "0101985123456"
      ime: Stefan
      prezime: Nikolić
      adresa: Knez Mihailova 11
      grad: Beograd
    tipKarte:
      tipKarteID: 1
      nazivKarte: Jednosmerna
    ruta:
      rutaID: 1
      mestoDolaska: Beograd
      mestoOdlaska: Novi Sad
      brojPosecenihStanica: 5
    autobus:
      autobusID: 1
      prevoznik: Banat Trans
      tipAutobusa: Standardni
      brojSedista: 50

  -
    kartaID: 3
    brojPerona: P3
    brojSedista: C1
    datumPolaska: 2023-06-12
    datumDolaska: 2023-06-13
    korisnik:
      korisnikID: 3
      JMBG: "0707918123456"
      ime: Milica
      prezime: Petrović
      adresa: Bulevar Nemanjića 13
      grad: Niš
    tipKarte:
      tipKarteID: 2
      nazivKarte: Povratna
    ruta:
      rutaID: 3
      mestoDolaska: Subotica
      mestoOdlaska: Novi Pazar
      brojPosecenihStanica: 4
    autobus:
      autobusID: 3 
      prevoznik: "Vojvodina Tours"
      tipAutobusa: "Mini bus"
      brojSedista: 20