#%RAML 1.0 NamedExample

value:

  -
    tipKarteID: 1
    nazivKarte: Jednosmerna

  -
    tipKarteID: 2
    nazivKarte: Povratna

  -
    tipKarteID: 3
    nazivKarte: Mesečna

  -
    tipKarteID: 4
    nazivKarte: Dnevna

  -
    tipKarteID: 5
    nazivKarte: Trodnevna