#%RAML 1.0 NamedExample

value:

  -
    korisnikID: 1
    JMBG: "0101985123456"
    ime: Stefan
    prezime: Nikolić
    adresa: Knez Mihailova 11
    grad: Beograd
  
  -
    korisnikID: 2
    JMBG: "2305947123456"
    ime: Ana
    prezime: Janković
    adresa: Trg Republike 12
    grad: Novi Sad

  -
    korisnikID: 3
    JMBG: "0707918123456"
    ime: Milica
    prezime: Petrović
    adresa: Bulevar Nemanjića 13
    grad: Niš