#%RAML 1.0 NamedExample

value:

  -
    zaposleniID: 1
    JMBG: "0101985123456"
    ime: Marko
    prezime: Petrović
    adresa: Knez Mihailova 1
    grad: Beograd
    brojSaltera: S1
    kontakt: "+381611234567"

  -
    zaposleniID: 2
    JMBG: "2305947123456"
    ime: Ana
    prezime: Jovanović
    adresa: Trg Republike 2
    grad: Novi Sad
    brojSaltera: S2
    kontakt: "+381641234567"

  -
    zaposleniID: 3
    JMBG: "0707918123456"
    ime: Milan
    prezime: Ilić
    adresa: Bulevar Nemanjića 3
    grad: Niš
    brojSaltera: S3
    kontakt: "+381601234567"