#%RAML 1.0 NamedExample
value:

  - 
    autobusID: 1 
    prevoznik: "Banat Trans"
    tipAutobusa: "Standardni"
    brojSedista: 50
  - 
    autobusID: 2 
    prevoznik: "Feniks Prevoz"
    tipAutobusa: "Dvospratni"
    brojSedista: 30

  - 
    autobusID: 3 
    prevoznik: "Vojvodina Tours"
    tipAutobusa: "Mini bus"
    brojSedista: 20
