#%RAML 1.0 NamedExample

value:

  -
    vozacID: 1
    JMBG: "0101985123456"
    ime: Marko
    prezime: Petrović
    adresa: Bulevar Oslobođenja 11
    grad: Beograd
    kontakt: "+381611234567"

  -
    vozacID: 2
    JMBG: "2305947123456"
    ime: Ana
    prezime: Jovanović
    adresa: Karađorđeva 22
    grad: Novi Sad
    kontakt: "+381641234567"

  -
    vozacID: 3
    JMBG: "0707918123456"
    ime: Milan
    prezime: Ilić
    adresa: Nemanjina 33
    grad: Niš
    kontakt: "+381601234567"
