#%RAML 1.0 NamedExample

value:

  -
    rutaID: 1
    mestoDolaska: Beograd
    mestoOdlaska: Novi Sad
    brojPosecenihStanica: 5

  -
    rutaID: 2
    mestoDolaska: Niš
    mestoOdlaska: Kragujevac
    brojPosecenihStanica: 3

  -
    rutaID: 3
    mestoDolaska: Subotica
    mestoOdlaska: Novi Pazar
    brojPosecenihStanica: 4
  