#%RAML 1.0 NamedExample
value:

  - 
    garazaID: 1 
    lokacija: "Novi Sad"
    brojGaraze: "G1"
  - 
    garazaID: 2 
    lokacija: "Beograd"
    brojGaraze: "G2"

  - 
    garazaID: 3 
    lokacija: "Niš"
    brojGaraze: "G3"